### ISSUE TITLE
Debian 10.4 : Mysql installation failure

### ISSUE THREAD

**Issue by xaviercm63** [aalaesar/install_nextcloud#103]
Hi,

"Target" OS : Debian 10.4
"Ansible" OS : Debian 10.4
Ansible : 2.7.7

Playbook:

```
---
- hosts: test
  become: yes
  roles:
   - role: aalaesar.install_nextcloud
```

I got this:

```
TASK [aalaesar.install_nextcloud : [mySQL: Debian] - Service is installed.] ******************************************************************************************************************
fatal: [192.168.0.155]: FAILED! => {"msg": "template error while templating string: unexpected char '&' at 58. String: {{ 'default-' if (ansible_distribution|lower) == 'debian' && nextcloud_db_backend == 'mysql' else '' }}{{ nextcloud_db_backend }}-server"}
```

Thanks!
