### ISSUE TITLE
How to install another version?

### ISSUE THREAD

**Issue by staticdev** [aalaesar/install_nextcloud#119]
@aalaesar I was trying to install the role with the playbook:

```
- hosts: all

  roles:
    - role: aalaesar.install_nextcloud
      nextcloud_version_full: "24.0.1"
      nextcloud_websrv: "apache2"
      nextcloud_webroot: "/var/www/nextcloud/"
      nextcloud_data_dir: "/ncdata"
      nextcloud_db_backend: "mariadb"
      nextcloud_tls_cert_method: "self-signed"
      become: true
```

Then I got some RedisExceptions on CRON (and list:apps). I tried to change the version of nextcloud_version_full but it was being skipped. So I deleted everything from `nextcloud_webroot` and `nextcloud_data_dir`. Now when I try to install other version I get:

```
TASK [aalaesar.install_nextcloud : [NC] - Run occ installation command] **************************************************************
fatal: [192.168.42.19]: FAILED! => {"changed": true, "cmd": ["php", "occ", "maintenance:install", "--database=mysql", "--database-host=127.0.0.1", "--database-name=nextcloud", "--database-user=ncadmin", "--database-pass=SxI8M4_VZyBjhM,jCiV8", "--admin-user=admin", "--admin-pass=ZF,yigPN:H", "--data-dir=/ncdata"], "delta": "0:00:00.196584", "end": "2022-06-20 09:03:35.943608", "msg": "non-zero return code", "rc": 1, "start": "2022-06-20 09:03:35.747024", "stderr": "", "stderr_lines": [], "stdout": "The username is already being used", "stdout_lines": ["The username is already being used"]}
```

How is the proper way to cleanup this user so I can try different versions?
