### ISSUE TITLE
Failed to execute in Ubuntu xenial

### ISSUE THREAD

**Issue by afonso360** [aalaesar/install_nextcloud#28]
Hi, tried to use this to install nextcloud on an ubuntu server xenial and got this error

Playbook:
```yaml
---
- name: Install Nextcloud
  hosts: nextcloud
  become: true

  vars:
    nextcloud_admin_name: "admin"
    nextcloud_db_admin: "ncadmin"

    nextcloud_apps:
      calendar: "https://github.com/nextcloud/calendar/releases/download/v1.5.0/calendar.tar.gz"
      contacts: "https://github.com/nextcloud/contacts/releases/download/v1.5.3/contacts.tar.gz"

  roles:
    - role: aalaesar.install_nextcloud
      tags: next
      nextcloud_trusted_domain:
        - "{{ domain_name }}"
      nextcloud_websrv: "nginx"
      nexcloud_db_backend: "pgsql"

      nextcloud_webroot: "/var/www/nextcloud/"
      nextcloud_data_dir: "/opt/ncdata"

      nextcloud_tls_cert_method: "installed"
      nextcloud_tls_cert: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      nextcloud_tls_cert_key: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
```

Error message:
```
 FAILED! => {"failed": true, "msg": "The conditional check 'nc_sudo_installed_result is defined and nc_sudo_installed_result.rc != 0' failed. The error was: error while evaluating conditional (nc_sudo_installed_result is defined and nc_sudo_installed_result.rc != 0): 'dict object' has no attribute 'rc'

The error appears to have been in '/etc/ansible/roles/aalaesar.install_nextcloud/tasks/setup_env.yml': line 31, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "[ENV] - rolling back to su."
  ^ here
"}
```
