### ISSUE TITLE
wont work via include_role

### ISSUE THREAD

**Issue by stephanfriedrich** [aalaesar/install_nextcloud#44]
hi thx for your role. 
i tried to run your role within an task but it wont work, all conditions will fail.

```
- name: "install nextclound service"
  become_user: 
  become: yes
  tags:
   -
 include_role:
    name: aalaesar.install_nextcloud
  vars:
```
