### ISSUE TITLE
[Solution: galaxy is not up to date] Ubuntu 18.04: Required and recommended packages are installed: 'php_ver' is undefined

### ISSUE THREAD

**Issue by klemens-u** [aalaesar/install_nextcloud#60]
OS: Ubuntu 18.04 
Playbook:

```
---
- name: test
  hosts: all
  remote_user: root
  vars: 
    nextcloud_trusted_domain:
      - "my.host.name"
    nextcloud_webroot: "/var/www/nextcloud"
    nextcloud_data_dir: "/srv/nextcloud"
  roles:
      # https://galaxy.ansible.com/aalaesar/install_nextcloud
     - aalaesar.install_nextcloud
```

Error:

> TASK [aalaesar.install_nextcloud : [APACHE] -  Required and recommended packages are installed.] ***
> fatal: [fresh1804srv]: FAILED! => {"msg": "'php_ver' is undefined"}
> 	to retry, use: --limit @/etc/ansible/site.retry
