### ISSUE TITLE
fix php memory_limit

### ISSUE THREAD

**Issue by mihailstoynov** [aalaesar/install_nextcloud#83]
>whenever going to Settings > Overview I keep getting the following error: "The PHP memory limit is below the recommended value of 512MB.

Source: https://help.nextcloud.com/t/the-php-memory-limit-is-below-the-recommended-value-of-512mb/42719

To fix it I do something outside the role to fix the php memory_limit:

```
- name: fix php memory limit
  lineinfile:
    path: /etc/php/7.2/fpm/php.ini
    regexp: ^memory_limit = .*$
    line: memory_limit = 512M
  notify: restart php7.2-fpm
```

You can incorporate it in the role.
